// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3JO52E6Hnp1_WbD7uM2MdB-HlykbymSY',
    appId: '1:145286602770:web:7b18a7db6b81abfd72f8cb',
    messagingSenderId: '145286602770',
    projectId: 'hobbyhub-d4158',
    authDomain: 'hobbyhub-d4158.firebaseapp.com',
    storageBucket: 'hobbyhub-d4158.firebasestorage.app',
    measurementId: 'G-NJ8GBLSJS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMTUBr8ICRDfaqmGv2CC1KZCQ8FsXfa78',
    appId: '1:145286602770:android:76648f1dce7227c472f8cb',
    messagingSenderId: '145286602770',
    projectId: 'hobbyhub-d4158',
    storageBucket: 'hobbyhub-d4158.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3JO52E6Hnp1_WbD7uM2MdB-HlykbymSY',
    appId: '1:145286602770:web:c0667ed66e1235f572f8cb',
    messagingSenderId: '145286602770',
    projectId: 'hobbyhub-d4158',
    authDomain: 'hobbyhub-d4158.firebaseapp.com',
    storageBucket: 'hobbyhub-d4158.firebasestorage.app',
    measurementId: 'G-Q4FLBCQEL6',
  );
}
